# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\testwind.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_l2(object):
    def setupUi(self, l2):
        l2.setObjectName("l2")
        l2.setEnabled(True)
        l2.resize(694, 637)
        self.setFixedSize(694, 637)
        self.left = 10
        self.top = 35
        self.width = 694
        self.height = 637
        self.setGeometry(self.left, self.top, self.width, self.height)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        l2.setFont(font)
        l2.setMouseTracking(False)
        l2.setWindowTitle("Form")
        l2.setToolTip("")
        l2.setAutoFillBackground(False)
        l2.setStyleSheet("")
        self.e1 = QtWidgets.QSlider(l2)
        self.e1.setGeometry(QtCore.QRect(20, 230, 19, 351))
        self.e1.setStyleSheet("")
        self.e1.setMinimum(200)
        self.e1.setMaximum(800)
        self.e1.setPageStep(1)
        self.e1.setProperty("value", 600)
        self.e1.setOrientation(QtCore.Qt.Vertical)
        self.e1.setObjectName("e1")
        self.e2 = QtWidgets.QSlider(l2)
        self.e2.setGeometry(QtCore.QRect(60, 230, 19, 351))
        self.e2.setMinimum(200)
        self.e2.setMaximum(800)
        self.e2.setPageStep(1)
        self.e2.setProperty("value", 600)
        self.e2.setOrientation(QtCore.Qt.Vertical)
        self.e2.setObjectName("e2")
        self.e3 = QtWidgets.QSlider(l2)
        self.e3.setGeometry(QtCore.QRect(100, 230, 19, 351))
        self.e3.setMinimum(200)
        self.e3.setMaximum(800)
        self.e3.setPageStep(1)
        self.e3.setProperty("value", 600)
        self.e3.setOrientation(QtCore.Qt.Vertical)
        self.e3.setObjectName("e3")
        self.e4 = QtWidgets.QSlider(l2)
        self.e4.setGeometry(QtCore.QRect(140, 230, 19, 351))
        self.e4.setMinimum(200)
        self.e4.setMaximum(800)
        self.e4.setPageStep(1)
        self.e4.setProperty("value", 600)
        self.e4.setOrientation(QtCore.Qt.Vertical)
        self.e4.setObjectName("e4")
        self.e5 = QtWidgets.QSlider(l2)
        self.e5.setGeometry(QtCore.QRect(180, 230, 19, 351))
        self.e5.setMinimum(200)
        self.e5.setMaximum(800)
        self.e5.setPageStep(1)
        self.e5.setProperty("value", 600)
        self.e5.setOrientation(QtCore.Qt.Vertical)
        self.e5.setObjectName("e5")
        self.e6 = QtWidgets.QSlider(l2)
        self.e6.setGeometry(QtCore.QRect(220, 230, 19, 351))
        self.e6.setMinimum(200)
        self.e6.setMaximum(800)
        self.e6.setPageStep(1)
        self.e6.setProperty("value", 600)
        self.e6.setOrientation(QtCore.Qt.Vertical)
        self.e6.setObjectName("e6")
        self.e7 = QtWidgets.QSlider(l2)
        self.e7.setGeometry(QtCore.QRect(260, 230, 19, 351))
        self.e7.setMinimum(200)
        self.e7.setMaximum(800)
        self.e7.setPageStep(1)
        self.e7.setProperty("value", 600)
        self.e7.setOrientation(QtCore.Qt.Vertical)
        self.e7.setObjectName("e7")
        self.e8 = QtWidgets.QSlider(l2)
        self.e8.setGeometry(QtCore.QRect(300, 230, 19, 351))
        self.e8.setMinimum(200)
        self.e8.setMaximum(800)
        self.e8.setPageStep(1)
        self.e8.setProperty("value", 600)
        self.e8.setOrientation(QtCore.Qt.Vertical)
        self.e8.setObjectName("e8")
        self.e9 = QtWidgets.QSlider(l2)
        self.e9.setGeometry(QtCore.QRect(340, 230, 19, 351))
        self.e9.setMinimum(200)
        self.e9.setMaximum(800)
        self.e9.setPageStep(1)
        self.e9.setProperty("value", 600)
        self.e9.setOrientation(QtCore.Qt.Vertical)
        self.e9.setObjectName("e9")
        self.e10 = QtWidgets.QSlider(l2)
        self.e10.setGeometry(QtCore.QRect(400, 230, 19, 351))
        self.e10.setMinimum(100)
        self.e10.setMaximum(400)
        self.e10.setPageStep(1)
        self.e10.setProperty("value", 200)
        self.e10.setOrientation(QtCore.Qt.Vertical)
        self.e10.setObjectName("e10")
        self.e11 = QtWidgets.QSlider(l2)
        self.e11.setGeometry(QtCore.QRect(450, 230, 19, 351))
        self.e11.setMinimum(100)
        self.e11.setMaximum(400)
        self.e11.setPageStep(1)
        self.e11.setProperty("value", 200)
        self.e11.setOrientation(QtCore.Qt.Vertical)
        self.e11.setObjectName("e11")
        self.l1 = QtWidgets.QLabel(l2)
        self.l1.setGeometry(QtCore.QRect(20, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.l1_2 = QtWidgets.QLabel(l2)
        self.l1_2.setGeometry(QtCore.QRect(60, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_2.setFont(font)
        self.l1_2.setObjectName("l1_2")
        self.l1_3 = QtWidgets.QLabel(l2)
        self.l1_3.setGeometry(QtCore.QRect(100, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_3.setFont(font)
        self.l1_3.setObjectName("l1_3")
        self.l1_4 = QtWidgets.QLabel(l2)
        self.l1_4.setGeometry(QtCore.QRect(140, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_4.setFont(font)
        self.l1_4.setObjectName("l1_4")
        self.l1_5 = QtWidgets.QLabel(l2)
        self.l1_5.setGeometry(QtCore.QRect(180, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_5.setFont(font)
        self.l1_5.setObjectName("l1_5")
        self.l1_6 = QtWidgets.QLabel(l2)
        self.l1_6.setGeometry(QtCore.QRect(220, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_6.setFont(font)
        self.l1_6.setObjectName("l1_6")
        self.l1_7 = QtWidgets.QLabel(l2)
        self.l1_7.setGeometry(QtCore.QRect(260, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_7.setFont(font)
        self.l1_7.setObjectName("l1_7")
        self.l1_8 = QtWidgets.QLabel(l2)
        self.l1_8.setGeometry(QtCore.QRect(300, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_8.setFont(font)
        self.l1_8.setObjectName("l1_8")
        self.l1_9 = QtWidgets.QLabel(l2)
        self.l1_9.setGeometry(QtCore.QRect(340, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_9.setFont(font)
        self.l1_9.setObjectName("l1_9")
        self.l1_10 = QtWidgets.QLabel(l2)
        self.l1_10.setGeometry(QtCore.QRect(400, 180, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_10.setFont(font)
        self.l1_10.setObjectName("l1_10")
        self.l1_11 = QtWidgets.QLabel(l2)
        self.l1_11.setGeometry(QtCore.QRect(450, 180, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1_11.setFont(font)
        self.l1_11.setObjectName("l1_11")
        self.t1 = QtWidgets.QTextBrowser(l2)
        self.t1.setEnabled(True)
        self.t1.setGeometry(QtCore.QRect(500, 230, 181, 31))
        self.t1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QTextBrowser(l2)
        self.t2.setGeometry(QtCore.QRect(500, 270, 181, 31))
        self.t2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t2.setObjectName("t2")
        self.t3 = QtWidgets.QTextBrowser(l2)
        self.t3.setGeometry(QtCore.QRect(500, 310, 181, 31))
        self.t3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t3.setObjectName("t3")
        self.t4 = QtWidgets.QTextBrowser(l2)
        self.t4.setGeometry(QtCore.QRect(500, 350, 181, 31))
        self.t4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t4.setObjectName("t4")
        self.t5 = QtWidgets.QTextBrowser(l2)
        self.t5.setGeometry(QtCore.QRect(500, 390, 181, 31))
        self.t5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t5.setObjectName("t5")
        self.t6 = QtWidgets.QTextBrowser(l2)
        self.t6.setGeometry(QtCore.QRect(500, 430, 181, 31))
        self.t6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t6.setObjectName("t6")
        self.t7 = QtWidgets.QTextBrowser(l2)
        self.t7.setGeometry(QtCore.QRect(500, 470, 181, 31))
        self.t7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t7.setObjectName("t7")
        self.t8 = QtWidgets.QTextBrowser(l2)
        self.t8.setGeometry(QtCore.QRect(500, 510, 181, 31))
        self.t8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t8.setObjectName("t8")
        self.t9 = QtWidgets.QTextBrowser(l2)
        self.t9.setGeometry(QtCore.QRect(500, 550, 181, 31))
        self.t9.setInputMethodHints(QtCore.Qt.ImhNone)
        self.t9.setObjectName("t9")
        self.label = QtWidgets.QLabel(l2)
        self.label.setGeometry(QtCore.QRect(530, 190, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(l2)
        self.line.setGeometry(QtCore.QRect(30, 160, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(l2)
        self.line_2.setGeometry(QtCore.QRect(410, 160, 41, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(l2)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(l2)
        self.label_3.setGeometry(QtCore.QRect(390, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.splitter_2 = QtWidgets.QSplitter(l2)
        self.splitter_2.setGeometry(QtCore.QRect(686, 15, 20, 101))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_3 = QtWidgets.QSplitter(l2)
        self.splitter_3.setGeometry(QtCore.QRect(30, 10, 431, 111))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.btn1 = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("")
        self.btn1.setObjectName("btn1")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btn4 = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("")
        self.btn4.setObjectName("btn4")
        self.btn3 = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("")
        self.btn3.setObjectName("btn3")
        self.btn5 = QtWidgets.QPushButton(l2)
        self.btn5.setGeometry(QtCore.QRect(500, 590, 181, 41))
        self.btn5.setObjectName("btn5")

        self.retranslateUi(l2)
        self.e1.valueChanged['int'].connect(self.l1.setNum)
        self.e2.valueChanged['int'].connect(self.l1_2.setNum)
        self.e3.valueChanged['int'].connect(self.l1_3.setNum)
        self.e4.valueChanged['int'].connect(self.l1_4.setNum)
        self.e5.valueChanged['int'].connect(self.l1_5.setNum)
        self.e6.valueChanged['int'].connect(self.l1_6.setNum)
        self.e7.valueChanged['int'].connect(self.l1_7.setNum)
        self.e8.valueChanged['int'].connect(self.l1_8.setNum)
        self.e9.valueChanged['int'].connect(self.l1_9.setNum)
        self.e10.valueChanged['int'].connect(self.l1_10.setNum)
        self.e11.valueChanged['int'].connect(self.l1_11.setNum)
        QtCore.QMetaObject.connectSlotsByName(l2)

    def retranslateUi(self, l2):
        _translate = QtCore.QCoreApplication.translate
        self.l1.setText(_translate("l2", "600"))
        self.l1_2.setText(_translate("l2", "600"))
        self.l1_3.setText(_translate("l2", "600"))
        self.l1_4.setText(_translate("l2", "600"))
        self.l1_5.setText(_translate("l2", "600"))
        self.l1_6.setText(_translate("l2", "600"))
        self.l1_7.setText(_translate("l2", "600"))
        self.l1_8.setText(_translate("l2", "600"))
        self.l1_9.setText(_translate("l2", "600"))
        self.l1_10.setText(_translate("l2", "200"))
        self.l1_11.setText(_translate("l2", "200"))
        self.label.setText(_translate("l2", "Prediction(Tp[°C])"))
        self.label_2.setText(_translate("l2", "Temperature of Radiation [°C]"))
        self.label_3.setText(_translate("l2", "Velocity [mm/s]"))
        self.btn1.setText(_translate("l2", "RUN"))
        self.btn4.setText(_translate("l2", "DELETE"))
        self.btn3.setText(_translate("l2", "PLOT"))
        self.btn5.setText(_translate("l2", "close"))

